In [2]:
import numpy as np
import pandas as pd

In [3]:
import scipy.stats as stats

In [4]:
dataset=pd.read_csv("C:\\Users\\nisha\\Downloads\\bank.csv")
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [5]:
dataset.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [6]:
dataset_table=pd.crosstab(dataset['housing'],dataset['deposit'])
print(dataset_table)

deposit    no   yes
housing            
no       2527  3354
yes      3346  1935


In [7]:
dataset_table.values

array([[2527, 3354],
       [3346, 1935]], dtype=int64)

In [8]:
observed_value=dataset_table.values
print("Observed Values:",observed_value)

Observed Values: [[2527 3354]
 [3346 1935]]


In [9]:
val=stats.chi2_contingency(dataset_table)
val

(463.1892407533161,
 9.724394114495535e-103,
 1,
 array([[3094.3480559, 2786.6519441],
        [2778.6519441, 2502.3480559]]))

In [10]:
expected_value=val[3]
expected_value

array([[3094.3480559, 2786.6519441],
       [2778.6519441, 2502.3480559]])

In [11]:
rows=len(dataset_table.iloc[0:2,0])
columns=len(dataset_table.iloc[0,0:2])
ddof=(columns-1)*(rows-1) 
print("degree of freedom",ddof)
alpha=0.05

degree of freedom 1


In [12]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(observed_value,expected_value)])
chi_square_statistic=chi_square[0]+chi_square[1]
chi_square_statistic

464.00673235222115

In [15]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print(p_value)


0.0


In [16]:
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
